1. σ_{dnum=5}(Empregado)
2. σ_{salario>3000}(Empregado)
3. σ_{dnum=5 ∧ salario>3000}(Empregado)
4. σ_{(dnum=5 ∧ salario>3000) ∨ (dnum=4 ∧ salario>2000)}(Empregado)
5. π_{pnome, salario}(Empregado)
6. π_{pnome, salario}(σ_{dnum=5}(Empregado))
7. π_{RG}(σ_{dnum=5}(Empregado)) ∪ π_{supRG}(σ_{dnum=5 ∧ supRG ≠ NULL}(Empregado))
8. π_{pnome}(Empregado) ∩ π_{dep_nome}(Dependente)
9. π_{Empregado.pnome, Dependente.dep_nome}(Empregado × Dependente)
10. π_{Empregado.pnome, Dependente.dep_nome}(Empregado ⋈_{Empregado.RG = Dependente.empRG} Dependente)
11. π_{Departamento.dnome, Empregado.pnome}(Departamento ⋈_{Departamento.gerRG = Empregado.RG} Empregado)
12. Departamento ⋈ Localização
13. π_{Empregado.pnome, Projeto.pnome}(Empregado ⋈_{Empregado.RG = Trabalha_em.RG} Trabalha_em ⋈_{Trabalha_em.pnum = Projeto.pnum} Projeto)
14. π_{Empregado.pnome}(Empregado ⋈_{Empregado.RG = Trabalha_em.RG} Trabalha_em ⋈_{Trabalha_em.pnum = Projeto.pnum} σ_{dnum=5}(Projeto))
15. γ_{count(RG)→num_emp}(Empregado)
16. γ_{dnum, count(RG)→num_emp}(Empregado)
17. γ_{dnum, avg(salario)→media_sal}(Empregado)
18. π_{Empregado.pnome, rua, cidade, estado}(Empregado ⋈_{Empregado.dnum = Departamento.dnum} σ_{dnome="Pesquisa"}(Departamento))
19. π_{Projeto.pnum, Projeto.dnum, Empregado.pnome, Empregado.sexo}(σ_{Projeto.localizacao="Londrina"}(Projeto) ⋈_{Projeto.dnum = Departamento.dnum} Departamento ⋈_{Departamento.gerRG = Empregado.RG} Empregado)